In [4]:
import torch
import pickle
import plotly.graph_objects as go
import sys
import os
from datagen.genset import GenSet

sys.path.append("./lib")

ROOT = "./"
device = "cpu"
# train = DataLoader(data_train, batch_size=None, shuffle=True, generator=torch.Generator(device=device))
# valid = DataLoader(data_valid, batch_size=None, shuffle=False, generator=torch.Generator(device=device))

with open(ROOT + "processed_datasets/data_valid.pt", "rb") as f:
  data_valid = torch.load(f, map_location=device)

In [33]:
gset = GenSet(4, 4, valid=True)
ex1 = next(iter(gset))
l1 = ex1[1][0].cpu()
ex1 = ex1[0][0].cpu()
ex2 = data_valid[0]
l2 = ex2[1]
ex2 = ex2[0]


y1 = ex1[:, 0]
s1 = ex1[:, 1]
x1 = ex1[:, 2]
print("ex1 is", l1)

y2 = ex2[:, 0]
s2 = ex2[:, 1]
x2 = ex2[:, 2]
print("ex2 is", l2)
s1

ex1 is tensor([0., 0., 1., 0.])
ex2 is tensor([1., 0., 0., 0.])


tensor([1.3044, 1.1724, 1.1665, 1.1687, 1.1533, 1.1654, 1.1703, 1.1646, 1.1632,
        1.1741, 1.1731, 1.1796, 1.1816, 1.1829, 1.1859, 1.2071, 1.1896, 1.2234,
        1.2157, 1.2386, 1.2490, 1.2744, 1.2851, 1.2860, 1.2727, 1.2925, 1.2908,
        1.2915, 1.2400, 1.2425, 1.2142, 1.2010, 1.2058, 1.1973, 1.1806, 1.1817,
        1.1728, 1.1699, 1.1798, 1.1636, 1.1681, 1.1635, 1.1781, 1.1896, 1.1922,
        1.2024, 1.2044, 1.2256, 1.2235, 1.2408, 1.2338, 1.3765, 1.3631, 1.3063,
        1.3086, 1.3024, 1.2748, 1.2545, 1.2375, 1.2257, 1.2126, 1.1998, 1.1843,
        1.1799, 1.1967, 1.1941, 1.1735, 1.1835, 1.1665, 1.1783, 1.1785, 1.1792,
        1.1913, 1.1752, 1.1810, 1.1835, 1.3373, 1.3458, 1.3497, 1.3553, 1.3579,
        1.3262, 1.3334, 1.3451, 1.3072, 1.2930, 1.2951, 1.2734, 1.2743, 1.2723,
        1.2412, 1.2444, 1.2287, 1.2090, 1.2091, 1.2067, 1.2144, 1.1835, 1.1957,
        1.1756, 1.1770, 1.1734, 1.1642, 1.2229, 1.2384, 1.2672, 1.2709, 1.2577,
        1.3020, 1.3187, 1.2997, 1.3119, 

In [20]:
s2

tensor([1.0401, 1.0457, 1.0493,  ..., 1.0441, 1.0493, 1.0462])

In [23]:
s1

tensor([0.4655, 0.4500, 0.4513, 0.4505, 0.4512, 0.4518, 0.4512, 0.4507, 0.4493,
        0.4503, 0.4497, 0.4501, 0.4503, 0.4509, 0.4518, 0.3889, 0.3871, 0.3874,
        0.3871, 0.3886, 0.3887, 0.3887, 0.3880, 0.3878, 0.3876, 0.3867, 0.3874,
        0.3870, 0.3872, 0.2385, 0.2382, 0.2381, 0.2377, 0.2362, 0.2368, 0.2367,
        0.2373, 0.2376, 0.2368, 0.2368, 0.2364, 0.2358, 0.2378, 0.0250, 0.0254,
        0.0254, 0.0245, 0.0245, 0.0244, 0.0241, 0.0247, 0.0237, 0.0237, 0.0232,
        0.0240, 0.0237, 0.0236, 0.4722, 0.4705, 0.4724, 0.4713, 0.4714, 0.4690,
        0.4711, 0.4706, 0.4710, 0.4714, 0.4711, 0.4707, 0.4706, 0.4723, 0.4710,
        0.4692, 0.4705, 0.4705, 0.4704, 0.4701, 0.4715, 0.4708, 0.4713, 0.4714,
        0.4704, 0.4708, 0.4701, 0.4706, 0.4708, 0.4715, 0.4710, 0.4706, 0.4701,
        0.4707, 0.4701, 0.4705, 0.4714, 0.4705, 0.4701, 0.4717, 0.4710, 0.4705,
        0.4711, 0.4727, 0.4700, 0.4706, 0.4708, 0.4706, 0.4722, 0.4703, 0.4700,
        0.4695, 0.4696, 0.4706, 0.4704, 

In [ ]:
fig = go.Figure()
fig.add_trace(go.Scatter(x=x1, y=y1, mode="markers", name="train"))
fig.add_trace(go.Scatter(x=x2, y=y2, mode="markers", name="valid"))
fig.show()